In [1]:
from datetime import datetime, timedelta
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import get_dados as gd

In [3]:
con = sqlite3.connect("dados_varias_coin.db")
bot_id = 1
df_bot_1 = pd.read_sql_query(f'SELECT * from operacoes_bot WHERE bot_id =={bot_id};', con)
bot_id = 2
df_bot_2 = pd.read_sql_query(f'SELECT * from operacoes_bot WHERE bot_id =={bot_id};', con)
con.close()

In [4]:
con = sqlite3.connect("dados_varias_coin.db")
ls_bot = pd.read_sql_query(f'SELECT * from bot;', con)
ls_bot.head()

,id,coin,qnt_brl_inicial,qnt_coin,qnt_brl_atual,grid_valor,limite_inferior,limite_superior,qnt_trade
0,1,XRP,20.0,0.49805,18.932961,0.06,1.90,3.1,0.5
1,2,XRP,20.0,0.49805,19.110669,0.04,2.25,2.7,0.5

In [5]:
(3.1 - 1.90) * 8

9.600000000000001

In [6]:
ultimo_valor_negociado = gd.get_ultimo_gravado("XRP")[5]

In [7]:
# df_bot_1.head()
df_bot_1

,id,bot_id,estado_ordem,v_tag_ordem,valor_compra,qnt_comprada,order_compra_id,time_compra,valor_venda,qnt_vendida,order_venda_id,time_venda,lucro,fee
0,5,1,finalizada,2.32,2.32928,0.5,40037174,1612711293,2.3857000599999996,0.49805,40227347.0,1.612793e+09,None,None
1,8,1,finalizada,2.38,2.37378,0.5,40056634,1612603061,2.4301435700000003,0.49805,40057510.0,1.612625e+09,None,None
2,12,1,finalizada,2.38,2.38952,0.5,40092337,1612626482,2.4458600500000003,0.49805,40096034.0,1.612628e+09,None,None
3,13,1,finalizada,2.44,2.42197,0.5,40093902,1612625810,2.47826157,0.49805,40094249.0,1.612844e+09,None,None
4,18,1,finalizada,2.38,2.38952,0.5,40098885,1612643602,2.4458600500000003,0.49805,40125459.0,1.612844e+09,None,None
5,22,1,finalizada,2.26,2.26904,0.5,40226833,1612711498,2.32555007,0.49805,40228150.0,1.612719e+09,None,None
6,24,1,finalizada,2.2,2.2088,0.5,40227578,1612714537,2.26541008,0.49805,40236939.0,1.612717e+09,None,None
7,28,1,compra_criada,2.26,2.26904,0.5,40245315,1612718976,2.32904,0.5,NaN,NaN,None,None
8,35,1,compra_criada,2.32,2.32928,0.5,40352624,1612795295,2.38928,0.5,NaN,NaN,None,None
9,39,1,finalizada,2.44,2.44976,0.5,40452085,1612861390,2.50601005,0.49805,40485554.0,1.612893e+09,None,None
10,41,1,venda_criada,2.5,2.51,0.5,40453474,1612846060,2.57,0.49805,40456580.0,1.612846e+09,None,None
11,47,1,compra_criada,2.38,2.38952,0.5,40485186,1612861408,2.44952,0.5,NaN,NaN,None,None

In [8]:
len(df_bot_2)
df_bot_2

,id,bot_id,estado_ordem,v_tag_ordem,valor_compra,qnt_comprada,order_compra_id,time_compra,valor_venda,qnt_vendida,order_venda_id,time_venda,lucro,fee
0,6,2,finalizada,2.33,2.33932,0.5,40037186,1612610214,2.37576494,0.49805,40069395.0,1.612612e+09,None,None
1,7,2,finalizada,2.37,2.37948,0.5,40055903,1612602611,2.41585494,0.49805,40056464.0,1.612624e+09,None,None
2,9,2,finalizada,2.65,2.37184,0.5,40060080,1612605900,2.40822635,0.49805,40060805.0,1.612624e+09,None,None
3,10,2,finalizada,2.33,2.33932,0.5,40073274,1612711280,2.37576494,0.49805,40227223.0,1.612793e+09,None,None
4,11,2,finalizada,2.41,2.40436,0.5,40090694,1612624446,2.44070776,0.49805,40091362.0,1.612625e+09,None,None
5,14,2,finalizada,2.41,2.41964,0.5,40093435,1612626215,2.4559549300000003,0.49805,40095174.0,1.612628e+09,None,None
6,15,2,finalizada,2.37,2.37948,0.5,40094705,1612643602,2.41585494,0.49805,40125442.0,1.612662e+09,None,None
7,16,2,finalizada,2.65,2.46108,0.5,40098467,1612627688,2.49733302,0.49805,40099230.0,1.612845e+09,None,None
8,17,2,finalizada,2.45,2.42448,0.5,40099719,1612628086,2.4607877,0.49805,40100151.0,1.612844e+09,None,None
9,19,2,finalizada,2.41,2.41964,0.5,40098960,1612632704,2.4559549300000003,0.49805,40109200.0,1.612844e+09,None,None
10,20,2,finalizada,2.37,2.37948,0.5,40153530,1612664511,2.41585494,0.49805,40157128.0,1.612793e+09,None,None
11,21,2,finalizada,2.29,2.29916,0.5,40226726,1612711498,2.33566495,0.49805,40228001.0,1.612719e+09,None,None
12,23,2,finalizada,2.25,2.259,0.5,40227461,1612711582,2.2955649499999997,0.49805,40228301.0,1.612713e+09,None,None
13,25,2,finalizada,2.25,2.259,0.5,40233525,1612713760,2.2955649499999997,0.49805,40234271.0,1.612717e+09,None,None
14,26,2,finalizada,2.21,2.21884,0.5,40236241,1612714537,2.2554549600000002,0.49805,40236897.0,1.612717e+09,None,None
15,27,2,finalizada,2.29,2.29916,0.5,40244850,1612720557,2.33566495,0.49805,40248515.0,1.612725e+09,None,None
16,29,2,compra_criada,2.25,2.259,0.5,40248772,1612720838,2.299,0.5,NaN,NaN,None,None
17,30,2,finalizada,2.29,2.29916,0.5,40258616,1612757409,2.33566495,0.49805,40304765.0,1.612765e+09,None,None
18,31,2,compra_criada,2.29,2.29916,0.5,40334254,1612787909,2.33916,0.5,NaN,NaN,None,None
19,32,2,finalizada,2.37,2.37948,0.5,40348413,1612793969,2.41585494,0.49805,40349488.0,1.612795e+09,None,None
20,33,2,compra_criada,2.33,2.33932,0.5,40349307,1612794044,2.37932,0.5,NaN,NaN,None,None
21,34,2,finalizada,2.37,2.37948,0.5,40350946,1612795257,2.41585494,0.49805,40353027.0,1.612801e+09,None,None
22,36,2,finalizada,2.37,2.37948,0.5,40367467,1612801738,2.41585494,0.49805,40369997.0,1.612829e+09,None,None
23,37,2,compra_criada,2.37,2.37948,0.5,40424829,1612829336,2.41948,0.5,NaN,NaN,None,None
24,38,2,finalizada,2.49,2.49996,0.5,40452246,1612844821,2.53616492,0.49805,40452823.0,1.612845e+09,None,None
25,40,2,finalizada,2.45,2.4598,0.5,40452653,1612860982,2.49606493,0.49805,40484327.0,1.612893e+09,None,None
26,42,2,finalizada,2.53,2.48365,0.5,40457651,1612847041,2.51986929,0.49805,40459990.0,1.612894e+09,None,None
27,43,2,finalizada,2.49,2.49996,0.5,40454827,1612846101,2.53616492,0.49805,40456762.0,1.612895e+09,None,None
28,44,2,finalizada,2.65,2.47413,0.5,40459982,1612847212,2.5103735200000004,0.49805,40460604.0,1.612849e+09,None,None
29,45,2,finalizada,2.65,2.48148,0.5,40466775,1612850836,2.5177025399999997,0.49805,40467438.0,1.612894e+09,None,None
30,46,2,finalizada,2.41,2.41964,0.5,40485169,1612861512,2.4559549300000003,0.49805,40485979.0,1.612862e+09,None,None
31,48,2,finalizada,2.41,2.41964,0.5,40486800,1612863385,2.4559549300000003,0.49805,40490179.0,1.612870e+09,None,None
32,49,2,compra_criada,2.41,2.41964,0.5,40514170,1612875790,2.45964,0.5,NaN,NaN,None,None
33,50,2,venda_criada,2.53,2.53237,0.5,40553466,1612894982,2.57237,0.49805,40554037.0,1.612895e+09,None,None
34,51,2,compra_criada,2.49,2.49996,0.5,40554318,1612895338,2.53996,0.5,NaN,NaN,None,None

In [9]:
def get_lucro(df):
    r_estado = df["estado_ordem"] =="finalizada"
    df_lucro = df[r_estado]
    df_lucro["valor_venda"] = df_lucro["valor_venda"].astype(float)
    df_lucro["qnt_vendida"] = df_lucro["qnt_vendida"].astype(float)
    df_lucro["valor_compra"] = df_lucro["valor_compra"].astype(float)
    df_lucro["qnt_comprada"] = df_lucro["qnt_comprada"].astype(float)
    def map_lucro(x):
        lucro = x["valor_venda"]* x["qnt_vendida"] - x["valor_compra"] * x["qnt_comprada"]
        return lucro

    if not df_lucro.empty:
        df_lucro["lucro"] = df_lucro.apply(map_lucro, axis =1 )
        lucro_total = sum(df_lucro["lucro"])
        print(f'O bot {df_lucro["bot_id"].iloc[0]} deu um lucro de {lucro_total}')
    return df_lucro, lucro_total

In [10]:
df_lucro_b1, lucro_1 = get_lucro(df_bot_1)
df_lucro_b2, lucro_2 = get_lucro(df_bot_2)

print(lucro_1 + lucro_2)

O bot 1 deu um lucro de 0.18796129877500012
O bot 2 deu um lucro de 0.37685441489500016
0.5648157136700003

<ipython-input-9-63660e8e1ccb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lucro["valor_venda"] = df_lucro["valor_venda"].astype(float)
<ipython-input-9-63660e8e1ccb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lucro["qnt_vendida"] = df_lucro["qnt_vendida"].astype(float)
<ipython-input-9-63660e8e1ccb>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lucro["valor_compra"] = df_lucro["valor_compra"].astype(float)
<ipython-input-9-63660e8e1ccb>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lucro["qnt_comprada"] = df_lucro["qnt_comprada"].astype(float)
<ipython-input-9-63660e8e1ccb>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lucro["lucro"] = df_lucro.apply(map_lucro, axis =1 )

In [11]:
def get_dinheiro_empenhado(df):
    r_estado = (df["estado_ordem"] == "compra_aberta") | (df["estado_ordem"] == "compra_criada") |  (df["estado_ordem"] == "compra_executada")
    df_dinheiro_empenhado = df[r_estado]
    def map_dinheiro_alocado(x):
        return  float(x["valor_compra"]) * float(x["qnt_comprada"])
    som_dinheiro_empenhado = 0
    if not df_dinheiro_empenhado.empty:
        df_dinheiro_empenhado["dinheiro_alocado"] = df_dinheiro_empenhado.apply(map_dinheiro_alocado, axis =1 )
        som_dinheiro_empenhado= sum(df_dinheiro_empenhado["dinheiro_alocado"])
    return df_dinheiro_empenhado, som_dinheiro_empenhado

In [12]:
de_1, sde_1 = get_dinheiro_empenhado(df_bot_1)
de_2, sde_2 = get_dinheiro_empenhado(df_bot_2)

<ipython-input-11-85659c072395>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dinheiro_empenhado["dinheiro_alocado"] = df_dinheiro_empenhado.apply(map_dinheiro_alocado, axis =1 )

In [13]:
# df_lucro.head()

In [14]:
def coin_empenhada(df):
    r_estado_venda = (df["estado_ordem"] == "venda_aberta") | (df["estado_ordem"] == "venda_criada") |  (df["estado_ordem"] == "venda_executada")

    df_coin_empenhada = df[r_estado_venda]
    
    def map_dinheiro_alocado(x):
        return float(x["qnt_comprada"])
    
    qnt_moeda_empenhada = 0
    if not df_coin_empenhada.empty:
        df_coin_empenhada["moeda_alocada"] = df_coin_empenhada.apply(map_dinheiro_alocado, axis =1 )
        qnt_moeda_empenhada = sum(df_coin_empenhada["moeda_alocada"])
        
    return df_coin_empenhada, qnt_moeda_empenhada

In [15]:
dce_1, qme_1= coin_empenhada(df_bot_1) # * ultimo_valor_negociado
dce_1, qme_2=  coin_empenhada(df_bot_2) # *ultimo_valor_negociado

<ipython-input-14-2726b42cdad6>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_coin_empenhada["moeda_alocada"] = df_coin_empenhada.apply(map_dinheiro_alocado, axis =1 )

In [16]:
qme_2

0.5

In [17]:
# df_dinheiro_empenhado.head()

In [18]:
# df_dinheiro_empenhado["order_venda_id"].dropna().astype('int')

In [19]:
dinheir_bot_1 = ls_bot[ls_bot["id"]==1]["qnt_brl_atual"].iloc[0] + lucro_1  + qme_1* ultimo_valor_negociado
dinheir_bot_2 = ls_bot[ls_bot["id"]==2]["qnt_brl_atual"].iloc[0] + lucro_2  + qme_2* ultimo_valor_negociado

In [20]:
print(dinheir_bot_1, dinheir_bot_2)

20.38093759755 20.74753882979

In [21]:
sde_1
sde_2

7.098279999999999

In [22]:
def get_lucro(valor_entrada, valor_saida, qnt_desejada):
    valor_pago = valor_entrada * qnt_desejada
    qnt_comprada_taxada = qnt_desejada * (1 - 0.3/100) 
#     print(valor_pago,qnt_comprada_taxada)
    valor_saida = qnt_comprada_taxada * valor_saida
    valor_saida_taxada =  valor_saida  * (1 - 0.3/100)
    lucro_pos_taxas = valor_saida_taxada - valor_pago
    return valor_pago, valor_saida_taxada, lucro_pos_taxas

In [23]:
get_lucro(2.38, 2.44, 1)

(2.38, 2.4253819599999997, 0.04538195999999983)

In [24]:
qnt_moeda = 0.5
saida = get_lucro(2.38, 2.42, qnt_moeda)[2] #+ get_lucro(2.38, 2.41, qnt_moeda)[2] + get_lucro(2.38, 2.41, qnt_moeda)[2]+ get_lucro(2.38, 2.41, qnt_moeda)[2] 
saida

0.01275088999999996

In [25]:
get_lucro(2.38, 2.44, qnt_moeda)[2] #+get_lucro(2.38, 2.44, qnt_moeda)[2]

0.022690979999999916

In [26]:
# def map_dinheiro_alocado(x):
#     return  float(x["valor_compra"]) * float(x["qnt_comprada"])

# def map_moeda(x):
#     pass

# if not df_dinheiro_empenhado.empty:
#     df_dinheiro_empenhado["dinheiro_alocado"] = df_dinheiro_empenhado.apply(map_dinheiro_alocado, axis =1 )
# def map_pot_lucro(x):
#     c = float(x["valor_compra"]) * float(x["qnt_comprada"])
#     v = float(x["valor_venda"]) * float(x["qnt_vendida"])
#     return v - c
# if not df_dinheiro_empenhado.empty:
#     df_dinheiro_empenhado["pot_lucro"] = df_dinheiro_empenhado.apply(map_pot_lucro, axis =1 )
#     qnt_total = 20
#     valor_alocado= sum(df_dinheiro_empenhado["dinheiro_alocado"])
#     por_alocada = valor_alocado/qnt_total * 100
#     qnt_lucro_possivel = sum(df_dinheiro_empenhado["pot_lucro"])
#     print(f"Esta alocado:{round(por_alocada,2)}%, {round(valor_alocado,3)}; e pode ganhar: {round(qnt_lucro_possivel,5)} reais")